(function() {
  window.zonesFloor1 = [
    { id: "sport", label: "Спортивный зал", color: "#87CEFA", info: "", add_info: "" },
    { id: "prep", label: "Преподавательская", color: "#D3D3D3", info: "Преподавательская спортивного зала", add_info: "" },
    { id: "sport_gym", label: "Тренажерный зал", color: "#87CEFA", info: "", add_info: "" },
    { id: "sport_gym2", label: "Тренажерный зал", color: "#87CEFA", info: "", add_info: "" },
    { id: "lab", label: "Лаборатория", color: "#D3D3D3", info: "", add_info: "" },
    { id: "check", label: "Аудитория демонстрационного экзамена", color: "#D3D3D3", info: "Обычная аудитория, просто без номера", add_info: "" },
    { id: "dressW", label: "Женская раздевалка", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "showW", label: "Женская душевая", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "showM", label: "Мужская душевая", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "dressM", label: "Мужская раздевалка", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "109", label: "109", color: "#D3D3D3", info: "Кафедра спортивных дисциплин и методики их преподавания", add_info: "" },
    { id: "110", label: "110", color: "#D3D3D3", info: "Кафедра теоретических основ физической культуры и спорта<br>Заведующий кафедрой", add_info: "" },
    { id: "111", label: "111", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "100(A)", label: "100(A)", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "dir", label: "Директорская", color: "#D3D3D3", info: "Директорская спортивного зала", add_info: "" },
    { id: "100", label: "100", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "sport_yoga", label: "Гимнастический зал", color: "#87CEFA", info: "", add_info: "" },
    { id: "inv", label: "Инвентарная", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "prep_2", label: "Преподавательская", color: "#D3D3D3", info: "Преподавательская спортивного зала", add_info: "" },
    { id: "107", label: "107", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "101A(6)", label: "101A(6)", color: "#D3D3D3", info: "", add_info: "" },
    { id: "106", label: "106", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "101A(7)", label: "101A(7)", color: "#D3D3D3", info: "Архивы", add_info: "" },
    { id: "101A(8)", label: "101A(8)", color: "#D3D3D3", info: "Тренерская", add_info: "" },
    { id: "101A(9)", label: "101A(9)", color: "#D3D3D3", info: "Учебный отдел", add_info: "" },
    { id: "101A(5)", label: "101A(5)", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "101A(4)", label: "101A(4)", color: "#D3D3D3", info: "Заведующий кафедрой спортивных дисциплин и методики их преподавания", add_info: "" },
    { id: "101A(3)", label: "101A(3)", color: "#D3D3D3", info: "Учебный отдел", add_info: "График работы:<br>пн-чт<br>10:00 - 18:00,<br>пт 10:00 - 17:00,<br>сб - 10:00 - 14:00<br>Перерыв 13:15 - 13:45" },
    { id: "211", label: "211", color: "#D3D3D3", info: "Вход со второго этажа по лестнице вниз", add_info: "" },
    { id: "212", label: "212", color: "#D3D3D3", info: "Вход со второго этажа по лестнице вниз", add_info: "" },
    { id: "ums", label: "УМС", color: "#D3D3D3", info: "Вход со второго этажа по лестнице вниз", add_info: "" },
    { id: "210", label: "210", color: "#D3D3D3", info: "Вход со второго этажа по лестнице вниз", add_info: "" },
    { id: "209", label: "209", color: "#D3D3D3", info: "Вход со второго этажа по лестнице вниз", add_info: "" },
    { id: "shtab", label: "Штаб студенческого спасательного отряда МПГУ", color: "#D3D3D3", info: "", add_info: "" },
    { id: "uvr", label: "УВР", color: "#FF6347", info: "Вход через лестницу в самом конце второго этажа после столовой, до конца вниз по лестнице", add_info: ""  },
    { id: "uvr_2", label: "УВР", color: "#FF6347", info: "Вход через лестницу в самом конце второго этажа после столовой, до конца вниз по лестнице", add_info: ""  },
    { id: "uvr_3", label: "УВР", color: "#FF6347", info: "Вход через лестницу в самом конце второго этажа после столовой, до конца вниз по лестнице", add_info: ""  },
    { id: "uvr_4", label: "УВР", color: "#FF6347", info: "Вход через лестницу в самом конце второго этажа после столовой, до конца вниз по лестнице", add_info: ""  },
    { id: "4", label: "203б(4)", color: "#D3D3D3", info: "Вход со второго этажа по лестнице напротив столовой", add_info: ""  },
    { id: "2", label: "203б(2)", color: "#D3D3D3", info: "Вход со второго этажа по лестнице напротив столовой", add_info: ""  },
    { id: "207", label: "207", color: "#D3D3D3", info: "Вход со второго этажа по лестнице вниз", add_info: ""  },
    { id: "205", label: "205", color: "#D3D3D3", info: "Вход со второго эта этажа по лестнице вниз", add_info: ""  },
    { id: "208", label: "208", color: "#D3D3D3", info: "Вход со второго этажа по лестнице вниз", add_info: "" },
    { id: "206", label: "206", color: "#D3D3D3", info: "Вход со второго этажа по лестнице вниз", add_info: "" },
    { id: "entrance", label: "Вход в здание", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "shop", label: "Буфет", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "actback", label: "Закулисье", color: "#ffe9ed", info: "", add_info: ""  },
    { id: "act", label: "Актовый зал", color: "#ffe9ed", info: "", add_info: "" },
    { id: "103", label: "103", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "102", label: "102", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "kassa", label: "Касса", color: "#FF6347", info: "", add_info: ""  },
    { id: "107_2", label: "107", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "108", label: "108", color: "#D3D3D3", info: "", add_info: ""  },
    { id: "3", label: "203б(3)", color: "#D3D3D3", info: "Вход со второго этажа по лестнице напротив столовой", add_info: "" },
    { id: "kaf_check", label: "Кафедра физического здоровья", color: "#FF6347", info: "", add_info: "" },
    { id: "kaf", label: "Центр развития ребенка", color: "#FF6347", info: "", add_info: "Режим работы:<br>Понедельник: 13:00 - 18:00<br>Четверг: 13:00 - 18:00" },
    { id: "ch", label: "Кафедра английского языка и цифровых образовательных технологий, Кафедра иноязычного образования", color: "#FF6347", info: "", add_info: "" },
    { id: "hz", label: "Отдел статистики", color: "#FF6347", info: "", add_info: "Приемные часы: 10:00 - 16:00" },
    { id: "chto", label: "Управление издательской деятельности", color: "#FF6347", info: "Начальник Управления - Алла Борисовна Чехович,<br>Начальник Редакционно-издательского отдела - Алла И. Ч.", add_info: "Алла Борисовна Чехович(+7 906 754 08 21),<br>Анна И. Н.(+7 915 015 015 8)" },
    { id: "az", label: "Управление издательской деятельности", color: "#FF6347", info: "", add_info: "" },
    { id: "che", label: "Учебно-методический центр", color: "#FF6347", info: "", add_info: "" },

    { id: "tW", label: "Женский туалет", color: "#98FB98", info: "", add_info: ""  },
    { id: "tM", label: "Мужской туалет", color: "#98FB98", info: "", add_info: ""  },
    { id: "el", label: "Лифт", color: "#4B0082", info: "", add_info: ""  },
    { id: "st", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "tW_2", label: "Женский туалет", color: "#98FB98", info: "", add_info: ""  },
    { id: "tM_2", label: "Мужской туалет", color: "#98FB98", info: "", add_info: ""  },
    { id: "el_2", label: "Лифт", color: "#4B0082", info: "", add_info: ""  },
    { id: "st_2", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "st_3", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "tW_3", label: "Женский туалет", color: "#98FB98", info: "", add_info: ""  },
    { id: "el_3", label: "Лифт", color: "#4B0082", info: "", add_info: ""  },
    { id: "st_4", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "st_5", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "st_6", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "st_7", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "st_8", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "st_9", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "st_10", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "st_11", label: "Лестница", color: "#E0FFFF", info: "", add_info: "" },
    { id: "tALL", label: "Общий туалет", color: "#98FB98", info: "", add_info: ""  },
    { id: "tALL_2", label: "Общий туалет", color: "#98FB98", info: "", add_info: ""  },
  ];
})();